spring:
  application:
    name: redis-learning-project

  # MySQL Configuration
  datasource:
    url: jdbc:mysql://localhost:3307/redis_learning?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: user
    password: user1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    open-in-view: false

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6380 # Redis의 기본 포트는 6379이며, 6380은 커스텀 포트
      timeout: 3000ms # Redis 서버와의 연결 및 응답을 기다리는 최대 시간(소켓 타임아웃)
      lettuce:
        pool:
          max-active: 10 # 커넥션 풀에서 동시에 사용(활성화)될 수 있는 최대 연결 수
          max-idle: 10 # 커넥션 풀에서 사용되지 않고 대기(유휴) 상태로 유지될 수 있는 최대 연결 수
          min-idle: 2 # 커넥션 풀에서 최소한으로 유지해야 하는 유휴 연결 수

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 캐시 데이터의 기본 만료 시간(TTL, Time-To-Live)을 밀리초(ms) 단위
      cache-null-values: false # 'null' 값을 캐시할지 여부를 설정

# Logging Configuration
logging:
  level:
    com.example.redis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG

# Server Configuration
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Management Configuration (for Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
